graph LR
subgraph ClientLayer["Client Layer", fill:#ccf,stroke:#000,stroke-width:2px]
    Web_App["Web App"]
    Mobile_App["Mobile App"]
end
subgraph APIGatewayLayer["API Gateway Layer", fill:#fcc,stroke:#000,stroke-width:2px]
    API_Gateway["API Gateway"]
end
subgraph CoreServicesLayer["Core Services Layer", fill:#cfc,stroke:#000,stroke-width:2px]
    ProductService["Product Service"]
    UserService["User Service"]
    OrderService["Order Service"]
    CartService["Cart Service"]
end
subgraph DatabaseLayer["Database Layer", fill:#ccf,stroke:#000,stroke-width:2px]
    ProductDB["Product Database"]
    UserDB["User Database"]
    OrderDB["Order Database"]
end
subgraph MessageBroker["Message Broker", fill:#fcf,stroke:#000,stroke-width:2px]
    MessageQueue["Message Queue"]
end
subgraph ExternalServices["External Services",fill:#ff9,stroke:#000,stroke-width:2px]
    PaymentGateway["Payment Gateway"]
    EmailService["Email Service"]
end
Web_App --> API_Gateway
Mobile_App --> API_Gateway
API_Gateway --> ProductService
API_Gateway --> UserService
API_Gateway --> OrderService
API_Gateway --> CartService
ProductService --> ProductDB
UserService --> UserDB
OrderService --> OrderDB
OrderService --> UserDB
CartService --> UserDB
CartService --> ProductDB
UserService --> MessageQueue
OrderService --> MessageQueue
MessageQueue --> PaymentGateway
MessageQueue --> EmailService
ProductService -.-> MessageQueue
style ProductService fill:#ccf,stroke:#000,stroke-width:2px
style UserService fill:#ccf,stroke:#000,stroke-width:2px
style OrderService fill:#ccf,stroke:#000,stroke-width:2px
style CartService fill:#ccf,stroke:#000,stroke-width:2px

