graph LR
subgraph Products
    A[/api/products GET] --> B[/api/products/{id} GET]
    C[/api/products POST]
    D[/api/products/{id} PUT]
end
subgraph Users
    E[/api/users GET] --> F[/api/users/{id} GET]
    G[/api/users POST]
    H[/api/users/{id} PUT]
    I[/api/users/{id} DELETE]
    J[/users GET] --> K[/users/:id GET]
    L[/users/register POST]
    M[/users/:id/cart POST] --> K[/users/:id GET]
    N[/users/:id/checkout POST] --> K[/users/:id GET]
end

